export const mockCrimeData = [
  {
    id: "1",
    category: "Theft",
    description: "Smartphone stolen from pedestrian by individual on bicycle.",
    latitude: "51.5151",
    longitude: "-0.1415",
    street_name: "Oxford Street",
    user_id: "user1",
    created_at: "2024-03-04T14:30:00Z",
    verified: true,
    votes: { upvotes: 5, downvotes: 1 },
    flags: 0,
  },
  {
    id: "2",
    category: "Criminal damage and arson",
    description: "Shop window broken during the night. CCTV footage being reviewed.",
    latitude: "51.5388",
    longitude: "-0.1424",
    street_name: "Camden High Street",
    user_id: "user2",
    created_at: "2024-03-03T03:15:00Z",
    verified: true,
    votes: { upvotes: 3, downvotes: 0 },
    flags: 0,
  },
  {
    id: "3",
    category: "Violence and sexual offences",
    description: "Verbal altercation escalated to physical confrontation outside pub.",
    latitude: "51.4651",
    longitude: "-0.1146",
    street_name: "Brixton Road",
    user_id: "user3",
    created_at: "2024-03-03T23:45:00Z",
    verified: false,
    votes: { upvotes: 12, downvotes: 2 },
    flags: 1,
  },
  {
    id: "4",
    category: "Anti-social behaviour",
    description: "Group of individuals seen testing car door handles in residential area.",
    latitude: "51.5712",
    longitude: "-0.1009",
    street_name: "Finsbury Park Road",
    user_id: "user4",
    created_at: "2024-03-02T02:20:00Z",
    verified: false,
    votes: { upvotes: 8, downvotes: 3 },
    flags: 2,
  },
  {
    id: "5",
    category: "Burglary",
    description: "Residential property broken into while occupants were away. Jewelry and electronics stolen.",
    latitude: "51.5016",
    longitude: "-0.1926",
    street_name: "Kensington High Street",
    user_id: "user5",
    created_at: "2024-03-01T16:45:00Z",
    verified: true,
    votes: { upvotes: 7, downvotes: 0 },
    flags: 0,
  },
]

